project:
  type: website
  output-dir: docs

website:
  title: "Nathan R. Jones"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: basic.qmd
        text: Basics
      - href: org.qmd
        text: Organization
      - href: projects.qmd
        text: Projects
      - href: functions.qmd
        text: Functions
      - href: sample_clean.qmd
        text: Sample Cleaning
      - href: reporting.qmd
        text: Reporting
      - href: weighting.qmd
        text: Weighting
    right:
      - icon: fa-envelope fa-lg
        href: contact.html
      - icon: fa-github fa-lg
        href: http://github.com/nrjjones

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

