project:
  type: website
  output-dir: docs

website:
  title: "Nathan R Jones"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: basic.qmd
        text: Getting started
      - href: projects.qmd
        text: RStudio projects
      - href: sample_clean.qmd
        text: Sample Cleaning
      - href: reporting.qmd
        text: Reporting
      - href: weighting.qmd
        text: Weighting
      - href: org.qmd
        text: Organization
      - href: functions.qmd
        text: Functions


    right:
      - icon: envelope
        href: contact.html
      - icon: github
        href: http://github.com/nrjjones

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

