---
title: "CV"
output: html_document
---

# Training and Education

**2001-2003     The RAND Corporation**

- National Institute on Aging Post-Doctoral Training Fellowship


**1997-2001     University of Pennsylvania**

- PhD, Demography, 2001

- AM, Demography, 1998

National Institute on Aging Pre-Doctoral Training Fellowship, 1998-2001.


**1993-1997     Emory University** 		                         

- BA/MA, Sociology, 1997



# Work Experience	

**2012-present	University of Wisconsin Survey Center**

Senior Project Director

- Consults with principal investigators on survey research and sampling methodologies.

- Manages and coordinates all aspects of surveys including research development, instrument design, application development, and supervision of survey staff.  

- Manages and analyzes data using statistical software packages including Stata, R, SAS, SPSS, and ArcGIS; writes technical documentation on survey methodology and responses rates; and provides analysis assistance to principal investigators.  

- International training and technical assistance in Chad, China (Tibet), Ethiopia, Philippines, and others.  

**2008-2012	University of Wisconsin – Carbone Cancer Center (UWCCC)**

Assistant Scientist

- Director of Survey Research Shared Service (SRSS), providing consultation and technical assistance to cancer center members and other researchers conducting mail, telephone, web-based, and multi-mode surveys.  

- Analyst for MATCH County Health Rankings in UW Population Health Institute.

- Epidemiologist with Wisconsin Cancer Control and Outreach Program.

- Principal investigator with UWCCC Nutritional Epidemiology unit.  

- Research collaborator with faculty and graduate students associated with UW Carbone Cancer Center and the Population Health Institute. 

- Principal investigator for UWCCC tobacco-related grants including Tobacco Surveillance and Evaluation, Training and Technical Assistance, Wisconsin WINS, and SmokeFree Wisconsin.


 
**2004-2008	CDC-Office on Smoking and Health**

Senior Service Fellow - Statistician/Demographer (GS-13)

- Helped coordinate the Global Tobacco Surveillance System (GTSS), a series of school-based surveys conducted in partnership with WHO that includes the Global Youth Tobacco Survey (GYTS), the Global School Personnel Survey (GSPS), the Global Health Professional Students Survey (GHPSS), and the Global Adult Tobacco Survey (GATS).  

- Provided logistical and technical support to survey coordinators in over 160 countries.  

- Teaching faculty for GTSS training and analysis workshops conducted in 6 WHO regions.  

- Consultant in the development of research protocols, survey instruments, and training materials for the GATS fielded in 15 developing countries during 2006-2007, part of the Bloomberg Worldwide Stop Smoking Initiative.  
- Served as consultant in the development of research protocols, survey instrument, and training materials for the GHPSS.  

- Extensive international experience conducting workshops in Barbados, Burkina Faso, Republic of Congo, Denmark, Egypt, Mexico, Philippines, Costa Rica, Switzerland, Thailand, and others.  